nota1 = input("Digite a priemira nota: ")
n1 = float(nota1)
nota2 = input("Digite a segunda nota: ")
n2 = float(nota2)
nota3 = input("Digite a terceira nota: ")
n3 = float(nota3)
nota4 = input("Digite a quarta nota: ")
n4 = float(nota4)
media = (n1 + n2 + n3 + n4) / 4
print("A média aritmética é ",media)